### ISSUE TITLE
Just sits on "Loading" when no apps exist

### ISSUE THREAD

**Issue by carimura** [fnproject/ui#5] opened 2017-08-24 01:29 UTC

**Comment by nigeldeakin** [comment] 2018-02-02 15:28
I tried this just now and it works for me. I see "No Apps":
![screenshot from 2018-02-02 15-25-49](https://user-images.githubusercontent.com/6053562/35740672-7ad859fc-082d-11e8-918d-337cf2119d43.png)
So perhaps it's been fixed.

(You can get stuck in a "Loading" state if an error occurs, such as the Fn server is not running. But if that happens you should see an error message popup at the top right)

Closing as either fixed or not reproduceable.

**Closed by nigeldeakin** 2018-02-02 15:28 UTC
